___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [5]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [6]:
import numpy as np
print(np.__version__)


1.19.2


Створити вектор з 10 елементів, заповнений одиницями:

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [8]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Створити матрицю 5 на 5, заповнену нулями:

In [9]:
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [10]:
import numpy as np
L = np.random.random(20)
print(L)

[0.85650509 0.46414513 0.15555472 0.19186821 0.98632737 0.7697097
 0.86373856 0.14272612 0.50554425 0.91928165 0.79752348 0.9805738
 0.57751443 0.01285281 0.29481066 0.79356105 0.43367236 0.07532048
 0.90548519 0.96301887]


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [11]:
import numpy as np
L = np.random.random(20)
print("Mean",np.std(L))
print("Median",np.mean(L))
print("Standart deviation",np.median(L))

Mean 0.2221134727705804
Median 0.4460959346427457
Standart deviation 0.5297377190743475


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [12]:
a = np.random.random ((4,2))
b = np.random.random ((2,2))
c = a.dot(b)
print (c)

[[0.40549229 0.65126878]
 [0.52616419 0.4768968 ]
 [0.9593112  0.87104845]
 [0.68599283 0.9286505 ]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [13]:
new_array = c
new_array = np.concatenate([np.diagonal(c[::-1,:], k)[::(2*(k % 2)-1)] for k in range(1-c.shape[0], c.shape[0])])
print(new_array)

[0.40549229 0.65126878 0.52616419 0.9593112  0.4768968  0.87104845
 0.68599283 0.9286505 ]


In [57]:
print("Мінімальне значення:",np.min(new_array))
print("Максимальне значення:",np.max(new_array))

Мінімальне значення: -1.0
Максимальне значення: 1.0


In [90]:
np.argmax (new_array) = 0

SyntaxError: cannot assign to function call (<ipython-input-90-d40a648ee902>, line 1)

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [89]:
new_array = np.corrcoef (c[0:],c[1:])

Дано матрицю. Знайти ранг матриці:

In [15]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [16]:
d = np.linalg.det(a)
print (d)

440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [17]:
v = np.linalg.eigh(a)
print (v)

(array([-14.30540864,  -4.34740072,  23.65280936]), array([[ 0.15315575,  0.88160309,  0.44645191],
       [ 0.63674998, -0.43353159,  0.6376518 ],
       [-0.75570681, -0.18661821,  0.62775861]]))


Знайдіть число, що найчастіше зустрічається в масиві:

In [26]:
import numpy as np
from scipy import stats

a = np.random.randint(0,10,50)
m = stats.mode(a)
print(m)

ModeResult(mode=array([6]), count=array([10]))


Виведіть лише парні числа, що діляться на 5:

SyntaxError: invalid syntax (<ipython-input-40-4ed98c2ef979>, line 2)

In [95]:
a = np.random.randint(0,10,50)
print (a)


[0 2 9 8 9 4 7 7 3 0 9 4 4 4 7 5 7 8 3 2 7 3 2 0 4 1 4 3 5 2 8 2 4 0 4 9 7
 4 3 6 2 2 9 3 6 1 5 2 7 8]


In [96]:
for i in range a:
    if i % 2 == 0 and i % 5 == 0:
    print(i)

SyntaxError: invalid syntax (<ipython-input-96-50ef177d7f5c>, line 1)

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [31]:
M1 = np.array([[2., 5.], [1., -10.]])
V1 = np.array([1., 3.])
print(np.linalg.solve(M1, V1))

[ 1.  -0.2]
